name = "# wrangler.toml
name = 'logistics'"
main = "worker/index.ts"
compatibility_date = "2026-08-10"
workers_dev = false

[assets]
directory = "./out"
binding = "ASSETS"
run_worker_first = ["/api/*"]
