var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hdke0j._.js")
R.c("server/chunks/ssr/061u_next_dist_esm_build_templates_app-page_0m6lj6j.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h9~8yd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03gymbb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p30wzj._.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_0epof36._.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_builtin_forbidden_0z-4qs2.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_builtin_unauthorized_0nfp2ft.js")
R.c("server/chunks/ssr/git_logistics__next-internal_server_app__not-found_page_actions_11abixf.js")
R.m(97501)
module.exports=R.m(97501).exports
