var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mop91c._.js")
R.c("server/chunks/ssr/061u_next_dist_esm_build_templates_app-page_0e1emah.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h9~8yd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03gymbb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p30wzj._.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_0epof36._.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_builtin_forbidden_0z-4qs2.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_builtin_unauthorized_0nfp2ft.js")
R.c("server/chunks/ssr/061u_next_dist_client_components_builtin_global-error_0vthj8..js")
R.c("server/chunks/ssr/git_logistics__next-internal_server_app_page_actions_0~ilw~_.js")
R.m(13473)
module.exports=R.m(13473).exports
